// Country flag mapping utility
export const getCountryFlag = (countryCode: string): string | null => {
  const flagMap: Record<string, string> = {
    'US': '🇺🇸',
    'USA': '🇺🇸',
    'United States': '🇺🇸',
    'GB': '🇬🇧',
    'UK': '🇬🇧',
    'United Kingdom': '🇬🇧',
    'DE': '🇩🇪',
    'Germany': '🇩🇪',
    'FR': '🇫🇷',
    'France': '🇫🇷',
    'CA': '🇨🇦',
    'Canada': '🇨🇦',
    'AU': '🇦🇺',
    'Australia': '🇦🇺',
    'JP': '🇯🇵',
    'Japan': '🇯🇵',
    'CN': '🇨🇳',
    'China': '🇨🇳',
    'IN': '🇮🇳',
    'India': '🇮🇳',
    'BR': '🇧🇷',
    'Brazil': '🇧🇷',
    'MX': '🇲🇽',
    'Mexico': '🇲🇽',
    'ES': '🇪🇸',
    'Spain': '🇪🇸',
    'IT': '🇮🇹',
    'Italy': '🇮🇹',
    'RU': '🇷🇺',
    'Russia': '🇷🇺',
    'NL': '🇳🇱',
    'Netherlands': '🇳🇱',
    'SE': '🇸🇪',
    'Sweden': '🇸🇪',
    'NO': '🇳🇴',
    'Norway': '🇳🇴',
    'DK': '🇩🇰',
    'Denmark': '🇩🇰',
    'FI': '🇫🇮',
    'Finland': '🇫🇮',
    'CH': '🇨🇭',
    'Switzerland': '🇨🇭',
    'AT': '🇦🇹',
    'Austria': '🇦🇹',
    'BE': '🇧🇪',
    'Belgium': '🇧🇪',
    'PT': '🇵🇹',
    'Portugal': '🇵🇹',
    'PL': '🇵🇱',
    'Poland': '🇵🇱',
    'CZ': '🇨🇿',
    'Czech Republic': '🇨🇿',
    'HU': '🇭🇺',
    'Hungary': '🇭🇺',
    'SK': '🇸🇰',
    'Slovakia': '🇸🇰',
    'SI': '🇸🇮',
    'Slovenia': '🇸🇮',
    'HR': '🇭🇷',
    'Croatia': '🇭🇷',
    'GR': '🇬🇷',
    'Greece': '🇬🇷',
    'TR': '🇹🇷',
    'Turkey': '🇹🇷',
    'IL': '🇮🇱',
    'Israel': '🇮🇱',
    'SA': '🇸🇦',
    'Saudi Arabia': '🇸🇦',
    'AE': '🇦🇪',
    'UAE': '🇦🇪',
    'United Arab Emirates': '🇦🇪',
    'EG': '🇪🇬',
    'Egypt': '🇪🇬',
    'ZA': '🇿🇦',
    'South Africa': '🇿🇦',
    'NG': '🇳🇬',
    'Nigeria': '🇳🇬',
    'KE': '🇰🇪',
    'Kenya': '🇰🇪',
    'KR': '🇰🇷',
    'South Korea': '🇰🇷',
    'TH': '🇹🇭',
    'Thailand': '🇹🇭',
    'VN': '🇻🇳',
    'Vietnam': '🇻🇳',
    'PH': '🇵🇭',
    'Philippines': '🇵🇭',
    'ID': '🇮🇩',
    'Indonesia': '🇮🇩',
    'MY': '🇲🇾',
    'Malaysia': '🇲🇾',
    'SG': '🇸🇬',
    'Singapore': '🇸🇬',
    'HK': '🇭🇰',
    'Hong Kong': '🇭🇰',
    'TW': '🇹🇼',
    'Taiwan': '🇹🇼',
    'NZ': '🇳🇿',
    'New Zealand': '🇳🇿',
    'AR': '🇦🇷',
    'Argentina': '🇦🇷',
    'CL': '🇨🇱',
    'Chile': '🇨🇱',
    'CO': '🇨🇴',
    'Colombia': '🇨🇴',
    'PE': '🇵🇪',
    'Peru': '🇵🇪',
  };

  return flagMap[countryCode] || null;
};

export const formatLocation = (country?: string, city?: string): string => {
  if (city && country) {
    return `${city}, ${country}`;
  } else if (country) {
    return country;
  } else if (city) {
    return city;
  }
  return 'Unknown location';
};