export { default as WebsiteQRForm } from './WebsiteQRForm'
export { default as PDFQRForm } from './PDFQRForm'
export { default as ImagesQRForm } from './ImagesQRForm'
export { default as VCardQRForm } from './VCardQRForm'
export { default as GenericQRForm } from './GenericQRForm'
